# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0j86nq66gkl72v3jgbb0kp53n2hsyzkgir9jdkzyr7sr3rfq5mmp";
    aarch64-linux = "0w8wj5v1gw8cgfh2vsyawg8hwwynsvsm87hbhlrpk1fpyl01p329";
    x86_64-darwin = "0y592y2paj0q58gkw8dm9xrbnsls4ph1r8j1dnprcylng7cgnz06";
    aarch64-darwin = "0mss7jjxwxxgm4xyrcnpsvws9q2g2ng98nhynzgb2whd4dhsvynf";
  };

  urlMap = {
    x86_64-linux = "https://github.com/getkonfi/konfi/releases/download/v1.0.0/konfi_1.0.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/getkonfi/konfi/releases/download/v1.0.0/konfi_1.0.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/getkonfi/konfi/releases/download/v1.0.0/konfi_1.0.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/getkonfi/konfi/releases/download/v1.0.0/konfi_1.0.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "konfi";
  version = "1.0.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./konfi $out/bin/konfi
  '';

  meta = {
    description = "TUI for editing dotfiles with cross-app theme sync.";
    homepage = "https://github.com/getkonfi/konfi";
    license = lib.licenses.mit;
    mainProgram = "konfi";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
