# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1gijas49kk3dfrkp4lnpxcjg089xmjy0vr6ms6f0vw339p0xkba5";
    aarch64-linux = "17kx7ps1fcw7ff6sgj1dj6cyjczzbycqia6zlx2pd0lmizwm3n22";
    x86_64-darwin = "1mrpnzgjqwrzn063lkmilapsfq697kkbpij8846qlrz58a2r7c0m";
    aarch64-darwin = "07gf2igdn306vf3d94c88ix3025cs358x4qfh1pbgqbwlawzq6yy";
  };

  urlMap = {
    x86_64-linux = "https://github.com/getkonfi/konfi/releases/download/v0.32.4/konfi_0.32.4_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/getkonfi/konfi/releases/download/v0.32.4/konfi_0.32.4_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/getkonfi/konfi/releases/download/v0.32.4/konfi_0.32.4_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/getkonfi/konfi/releases/download/v0.32.4/konfi_0.32.4_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "konfi";
  version = "0.32.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./konfi $out/bin/konfi
  '';

  meta = {
    description = "TUI for editing dotfiles with cross-app theme sync.";
    homepage = "https://github.com/getkonfi/konfi";
    license = lib.licenses.mit;
    mainProgram = "konfi";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
